holidays:
  - 2025-11-27  # Thanksgiving
  - 2025-12-25  # Christmas
  - 2026-01-01  # New Year's Day
holiday_ranges:
  - [2025-07-01, 2025-07-06]  # Summer Break

first_data_date: 2025-01-01  # First date for which data is collected