pwd = 'e^7i=Cos7+iSin7'
hostname = 's-9b0f88558b264dfda.server.transfer.us-east-1.amazonaws.com'
export_id = '151717'
username='VvItalianExperienceExportUser'

main_dir = 'C:\Users\Jeremiah\OneDrive\Documents\VV\Daily_Order_Data\data_dashboard_streamlit\'
data_dir = 'C:\Users\Jeremiah\OneDrive\Documents\VV\Daily_Order_Data\data_dashboard_streamlit\Data\'